@file:Suppress("warnings")
/*
 * This file is generated by jOOQ.
 */
package au.concepta.sakila.database.indexes


import au.concepta.sakila.database.tables.Actor
import au.concepta.sakila.database.tables.Address
import au.concepta.sakila.database.tables.City
import au.concepta.sakila.database.tables.Customer
import au.concepta.sakila.database.tables.Film
import au.concepta.sakila.database.tables.FilmActor
import au.concepta.sakila.database.tables.Inventory
import au.concepta.sakila.database.tables.PaymentP2022_01
import au.concepta.sakila.database.tables.PaymentP2022_02
import au.concepta.sakila.database.tables.PaymentP2022_03
import au.concepta.sakila.database.tables.PaymentP2022_04
import au.concepta.sakila.database.tables.PaymentP2022_05
import au.concepta.sakila.database.tables.PaymentP2022_06
import au.concepta.sakila.database.tables.Rental
import au.concepta.sakila.database.tables.RentalByCategory
import au.concepta.sakila.database.tables.Store

import org.jooq.Index
import org.jooq.impl.DSL
import org.jooq.impl.Internal



// -------------------------------------------------------------------------
// INDEX definitions
// -------------------------------------------------------------------------

val FILM_FULLTEXT_IDX: Index = Internal.createIndex(DSL.name("film_fulltext_idx"), Film.FILM, arrayOf(Film.FILM.FULLTEXT), false)
val IDX_ACTOR_LAST_NAME: Index = Internal.createIndex(DSL.name("idx_actor_last_name"), Actor.ACTOR, arrayOf(Actor.ACTOR.LAST_NAME), false)
val IDX_FK_ADDRESS_ID: Index = Internal.createIndex(DSL.name("idx_fk_address_id"), Customer.CUSTOMER, arrayOf(Customer.CUSTOMER.ADDRESS_ID), false)
val IDX_FK_CITY_ID: Index = Internal.createIndex(DSL.name("idx_fk_city_id"), Address.ADDRESS, arrayOf(Address.ADDRESS.CITY_ID), false)
val IDX_FK_COUNTRY_ID: Index = Internal.createIndex(DSL.name("idx_fk_country_id"), City.CITY, arrayOf(City.CITY.COUNTRY_ID), false)
val IDX_FK_FILM_ID: Index = Internal.createIndex(DSL.name("idx_fk_film_id"), FilmActor.FILM_ACTOR, arrayOf(FilmActor.FILM_ACTOR.FILM_ID), false)
val IDX_FK_INVENTORY_ID: Index = Internal.createIndex(DSL.name("idx_fk_inventory_id"), Rental.RENTAL, arrayOf(Rental.RENTAL.INVENTORY_ID), false)
val IDX_FK_LANGUAGE_ID: Index = Internal.createIndex(DSL.name("idx_fk_language_id"), Film.FILM, arrayOf(Film.FILM.LANGUAGE_ID), false)
val IDX_FK_ORIGINAL_LANGUAGE_ID: Index = Internal.createIndex(DSL.name("idx_fk_original_language_id"), Film.FILM, arrayOf(Film.FILM.ORIGINAL_LANGUAGE_ID), false)
val IDX_FK_PAYMENT_P2022_01_CUSTOMER_ID: Index = Internal.createIndex(DSL.name("idx_fk_payment_p2022_01_customer_id"), PaymentP2022_01.PAYMENT_P2022_01, arrayOf(PaymentP2022_01.PAYMENT_P2022_01.CUSTOMER_ID), false)
val IDX_FK_PAYMENT_P2022_01_STAFF_ID: Index = Internal.createIndex(DSL.name("idx_fk_payment_p2022_01_staff_id"), PaymentP2022_01.PAYMENT_P2022_01, arrayOf(PaymentP2022_01.PAYMENT_P2022_01.STAFF_ID), false)
val IDX_FK_PAYMENT_P2022_02_CUSTOMER_ID: Index = Internal.createIndex(DSL.name("idx_fk_payment_p2022_02_customer_id"), PaymentP2022_02.PAYMENT_P2022_02, arrayOf(PaymentP2022_02.PAYMENT_P2022_02.CUSTOMER_ID), false)
val IDX_FK_PAYMENT_P2022_02_STAFF_ID: Index = Internal.createIndex(DSL.name("idx_fk_payment_p2022_02_staff_id"), PaymentP2022_02.PAYMENT_P2022_02, arrayOf(PaymentP2022_02.PAYMENT_P2022_02.STAFF_ID), false)
val IDX_FK_PAYMENT_P2022_03_CUSTOMER_ID: Index = Internal.createIndex(DSL.name("idx_fk_payment_p2022_03_customer_id"), PaymentP2022_03.PAYMENT_P2022_03, arrayOf(PaymentP2022_03.PAYMENT_P2022_03.CUSTOMER_ID), false)
val IDX_FK_PAYMENT_P2022_03_STAFF_ID: Index = Internal.createIndex(DSL.name("idx_fk_payment_p2022_03_staff_id"), PaymentP2022_03.PAYMENT_P2022_03, arrayOf(PaymentP2022_03.PAYMENT_P2022_03.STAFF_ID), false)
val IDX_FK_PAYMENT_P2022_04_CUSTOMER_ID: Index = Internal.createIndex(DSL.name("idx_fk_payment_p2022_04_customer_id"), PaymentP2022_04.PAYMENT_P2022_04, arrayOf(PaymentP2022_04.PAYMENT_P2022_04.CUSTOMER_ID), false)
val IDX_FK_PAYMENT_P2022_04_STAFF_ID: Index = Internal.createIndex(DSL.name("idx_fk_payment_p2022_04_staff_id"), PaymentP2022_04.PAYMENT_P2022_04, arrayOf(PaymentP2022_04.PAYMENT_P2022_04.STAFF_ID), false)
val IDX_FK_PAYMENT_P2022_05_CUSTOMER_ID: Index = Internal.createIndex(DSL.name("idx_fk_payment_p2022_05_customer_id"), PaymentP2022_05.PAYMENT_P2022_05, arrayOf(PaymentP2022_05.PAYMENT_P2022_05.CUSTOMER_ID), false)
val IDX_FK_PAYMENT_P2022_05_STAFF_ID: Index = Internal.createIndex(DSL.name("idx_fk_payment_p2022_05_staff_id"), PaymentP2022_05.PAYMENT_P2022_05, arrayOf(PaymentP2022_05.PAYMENT_P2022_05.STAFF_ID), false)
val IDX_FK_PAYMENT_P2022_06_CUSTOMER_ID: Index = Internal.createIndex(DSL.name("idx_fk_payment_p2022_06_customer_id"), PaymentP2022_06.PAYMENT_P2022_06, arrayOf(PaymentP2022_06.PAYMENT_P2022_06.CUSTOMER_ID), false)
val IDX_FK_PAYMENT_P2022_06_STAFF_ID: Index = Internal.createIndex(DSL.name("idx_fk_payment_p2022_06_staff_id"), PaymentP2022_06.PAYMENT_P2022_06, arrayOf(PaymentP2022_06.PAYMENT_P2022_06.STAFF_ID), false)
val IDX_FK_STORE_ID: Index = Internal.createIndex(DSL.name("idx_fk_store_id"), Customer.CUSTOMER, arrayOf(Customer.CUSTOMER.STORE_ID), false)
val IDX_LAST_NAME: Index = Internal.createIndex(DSL.name("idx_last_name"), Customer.CUSTOMER, arrayOf(Customer.CUSTOMER.LAST_NAME), false)
val IDX_STORE_ID_FILM_ID: Index = Internal.createIndex(DSL.name("idx_store_id_film_id"), Inventory.INVENTORY, arrayOf(Inventory.INVENTORY.STORE_ID, Inventory.INVENTORY.FILM_ID), false)
val IDX_TITLE: Index = Internal.createIndex(DSL.name("idx_title"), Film.FILM, arrayOf(Film.FILM.TITLE), false)
val IDX_UNQ_MANAGER_STAFF_ID: Index = Internal.createIndex(DSL.name("idx_unq_manager_staff_id"), Store.STORE, arrayOf(Store.STORE.MANAGER_STAFF_ID), true)
val IDX_UNQ_RENTAL_RENTAL_DATE_INVENTORY_ID_CUSTOMER_ID: Index = Internal.createIndex(DSL.name("idx_unq_rental_rental_date_inventory_id_customer_id"), Rental.RENTAL, arrayOf(Rental.RENTAL.RENTAL_DATE, Rental.RENTAL.INVENTORY_ID, Rental.RENTAL.CUSTOMER_ID), true)
val PAYMENT_P2022_01_CUSTOMER_ID_IDX: Index = Internal.createIndex(DSL.name("payment_p2022_01_customer_id_idx"), PaymentP2022_01.PAYMENT_P2022_01, arrayOf(PaymentP2022_01.PAYMENT_P2022_01.CUSTOMER_ID), false)
val PAYMENT_P2022_02_CUSTOMER_ID_IDX: Index = Internal.createIndex(DSL.name("payment_p2022_02_customer_id_idx"), PaymentP2022_02.PAYMENT_P2022_02, arrayOf(PaymentP2022_02.PAYMENT_P2022_02.CUSTOMER_ID), false)
val PAYMENT_P2022_03_CUSTOMER_ID_IDX: Index = Internal.createIndex(DSL.name("payment_p2022_03_customer_id_idx"), PaymentP2022_03.PAYMENT_P2022_03, arrayOf(PaymentP2022_03.PAYMENT_P2022_03.CUSTOMER_ID), false)
val PAYMENT_P2022_04_CUSTOMER_ID_IDX: Index = Internal.createIndex(DSL.name("payment_p2022_04_customer_id_idx"), PaymentP2022_04.PAYMENT_P2022_04, arrayOf(PaymentP2022_04.PAYMENT_P2022_04.CUSTOMER_ID), false)
val PAYMENT_P2022_05_CUSTOMER_ID_IDX: Index = Internal.createIndex(DSL.name("payment_p2022_05_customer_id_idx"), PaymentP2022_05.PAYMENT_P2022_05, arrayOf(PaymentP2022_05.PAYMENT_P2022_05.CUSTOMER_ID), false)
val PAYMENT_P2022_06_CUSTOMER_ID_IDX: Index = Internal.createIndex(DSL.name("payment_p2022_06_customer_id_idx"), PaymentP2022_06.PAYMENT_P2022_06, arrayOf(PaymentP2022_06.PAYMENT_P2022_06.CUSTOMER_ID), false)
val RENTAL_CATEGORY: Index = Internal.createIndex(DSL.name("rental_category"), RentalByCategory.RENTAL_BY_CATEGORY, arrayOf(RentalByCategory.RENTAL_BY_CATEGORY.CATEGORY), true)
