database {
  url = "jdbc:postgresql://localhost:15432/postgres"
  username = postgres
  password = not_secure
  poolSize = 10
}
ktor {
  deployment {
    port = 8080
  }
  application {
    modules = [
      au.concepta.sakila.ApplicationKt.module,
      au.concepta.sakila.infra.DatabaseModuleKt.databaseModule,
      au.concepta.sakila.infra.LoginModuleKt.loginModule,
      au.concepta.sakila.stores.StoreModuleKt.storeModule,
    ]
  }
}

jwt {
  secret = "secret"
  issuer = "http://0.0.0.0:8080/"
  audience = "http://0.0.0.0:8080/sakila"
  realm = "Sakila Web App"
}