database {
  url = "jdbc:postgresql://localhost:15432/postgres"
  username = postgres
  password = not_secure
  poolSize = 10
}
ktor {
  deployment {
    port = 8080
  }
  application {
    modules = [au.concepta.sakila.ApplicationKt.module]
  }
}