/*
 * This file is generated by jOOQ.
 */
package au.concepta.sakila.database.enums


import au.concepta.sakila.database.Public

import org.jooq.Catalog
import org.jooq.EnumType
import org.jooq.Schema


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
enum class MpaaRating(@get:JvmName("literal") public val literal: String) : EnumType {
    G("G"),
    PG("PG"),
    `PG-13`("PG-13"),
    R("R"),
    `NC-17`("NC-17");
    override fun getCatalog(): Catalog? = schema.catalog
    override fun getSchema(): Schema = Public.PUBLIC
    override fun getName(): String = "mpaa_rating"
    override fun getLiteral(): String = literal
}
