/*
 * This file is generated by jOOQ.
 */
package au.concepta.sakila.database.tables


import au.concepta.sakila.database.Public
import au.concepta.sakila.database.tables.records.FilmInStockRecord

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Record
import org.jooq.Schema
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class FilmInStock(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, FilmInStockRecord>?,
    parentPath: InverseForeignKey<out Record, FilmInStockRecord>?,
    aliased: Table<FilmInStockRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<FilmInStockRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.function(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.film_in_stock</code>
         */
        val FILM_IN_STOCK: FilmInStock = FilmInStock()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<FilmInStockRecord> = FilmInStockRecord::class.java

    /**
     * The column <code>public.film_in_stock.p_film_count</code>.
     */
    val P_FILM_COUNT: TableField<FilmInStockRecord, Int?> = createField(DSL.name("p_film_count"), SQLDataType.INTEGER, this, "")

    private constructor(alias: Name, aliased: Table<FilmInStockRecord>?): this(alias, null, null, null, aliased, arrayOf(
        DSL.value(null, SQLDataType.INTEGER),
        DSL.value(null, SQLDataType.INTEGER)
    ), null)
    private constructor(alias: Name, aliased: Table<FilmInStockRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)

    /**
     * Create an aliased <code>public.film_in_stock</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.film_in_stock</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.film_in_stock</code> table reference
     */
    constructor(): this(DSL.name("film_in_stock"), null)
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun `as`(alias: String): FilmInStock = FilmInStock(DSL.name(alias), this, parameters)
    override fun `as`(alias: Name): FilmInStock = FilmInStock(alias, this, parameters)
    override fun `as`(alias: Table<*>): FilmInStock = FilmInStock(alias.qualifiedName, this, parameters)

    /**
     * Rename this table
     */
    override fun rename(name: String): FilmInStock = FilmInStock(DSL.name(name), null, parameters)

    /**
     * Rename this table
     */
    override fun rename(name: Name): FilmInStock = FilmInStock(name, null, parameters)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): FilmInStock = FilmInStock(name.qualifiedName, null, parameters)

    /**
     * Call this table-valued function
     */
    fun call(
          pFilmId: Int?
        , pStoreId: Int?
    ): FilmInStock = FilmInStock(DSL.name("film_in_stock"), null, arrayOf(
        DSL.value(pFilmId, SQLDataType.INTEGER),
        DSL.value(pStoreId, SQLDataType.INTEGER)
    )).let { if (aliased()) it.`as`(unqualifiedName) else it }

    /**
     * Call this table-valued function
     */
    fun call(
          pFilmId: Field<Int?>
        , pStoreId: Field<Int?>
    ): FilmInStock = FilmInStock(DSL.name("film_in_stock"), null, arrayOf(
        pFilmId,
        pStoreId
    )).let { if (aliased()) it.`as`(unqualifiedName) else it }
}
