/*
 * This file is generated by jOOQ.
 */
package au.concepta.sakila.database.tables


import au.concepta.sakila.database.Public
import au.concepta.sakila.database.keys.PAYMENT_P2022_07_PKEY
import au.concepta.sakila.database.tables.records.PaymentP2022_07Record

import java.math.BigDecimal
import java.time.OffsetDateTime

import kotlin.collections.Collection

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class PaymentP2022_07(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, PaymentP2022_07Record>?,
    parentPath: InverseForeignKey<out Record, PaymentP2022_07Record>?,
    aliased: Table<PaymentP2022_07Record>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<PaymentP2022_07Record>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.payment_p2022_07</code>
         */
        val PAYMENT_P2022_07: PaymentP2022_07 = PaymentP2022_07()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<PaymentP2022_07Record> = PaymentP2022_07Record::class.java

    /**
     * The column <code>public.payment_p2022_07.payment_id</code>.
     */
    val PAYMENT_ID: TableField<PaymentP2022_07Record, Int?> = createField(DSL.name("payment_id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "")

    /**
     * The column <code>public.payment_p2022_07.customer_id</code>.
     */
    val CUSTOMER_ID: TableField<PaymentP2022_07Record, Int?> = createField(DSL.name("customer_id"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>public.payment_p2022_07.staff_id</code>.
     */
    val STAFF_ID: TableField<PaymentP2022_07Record, Int?> = createField(DSL.name("staff_id"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>public.payment_p2022_07.rental_id</code>.
     */
    val RENTAL_ID: TableField<PaymentP2022_07Record, Int?> = createField(DSL.name("rental_id"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>public.payment_p2022_07.amount</code>.
     */
    val AMOUNT: TableField<PaymentP2022_07Record, BigDecimal?> = createField(DSL.name("amount"), SQLDataType.NUMERIC(5, 2).nullable(false), this, "")

    /**
     * The column <code>public.payment_p2022_07.payment_date</code>.
     */
    val PAYMENT_DATE: TableField<PaymentP2022_07Record, OffsetDateTime?> = createField(DSL.name("payment_date"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<PaymentP2022_07Record>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<PaymentP2022_07Record>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<PaymentP2022_07Record>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.payment_p2022_07</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.payment_p2022_07</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.payment_p2022_07</code> table reference
     */
    constructor(): this(DSL.name("payment_p2022_07"), null)
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIdentity(): Identity<PaymentP2022_07Record, Int?> = super.getIdentity() as Identity<PaymentP2022_07Record, Int?>
    override fun getPrimaryKey(): UniqueKey<PaymentP2022_07Record> = PAYMENT_P2022_07_PKEY
    override fun `as`(alias: String): PaymentP2022_07 = PaymentP2022_07(DSL.name(alias), this)
    override fun `as`(alias: Name): PaymentP2022_07 = PaymentP2022_07(alias, this)
    override fun `as`(alias: Table<*>): PaymentP2022_07 = PaymentP2022_07(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): PaymentP2022_07 = PaymentP2022_07(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): PaymentP2022_07 = PaymentP2022_07(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): PaymentP2022_07 = PaymentP2022_07(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): PaymentP2022_07 = PaymentP2022_07(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): PaymentP2022_07 = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): PaymentP2022_07 = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): PaymentP2022_07 = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): PaymentP2022_07 = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): PaymentP2022_07 = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): PaymentP2022_07 = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): PaymentP2022_07 = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): PaymentP2022_07 = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): PaymentP2022_07 = where(DSL.notExists(select))
}
