/*
 * This file is generated by jOOQ.
 */
package au.concepta.sakila.database.tables


import au.concepta.sakila.database.Public
import au.concepta.sakila.database.indexes.IDX_FK_PAYMENT_P2022_06_CUSTOMER_ID
import au.concepta.sakila.database.indexes.IDX_FK_PAYMENT_P2022_06_STAFF_ID
import au.concepta.sakila.database.indexes.PAYMENT_P2022_06_CUSTOMER_ID_IDX
import au.concepta.sakila.database.keys.PAYMENT_P2022_06_PKEY
import au.concepta.sakila.database.keys.PAYMENT_P2022_06__PAYMENT_P2022_06_CUSTOMER_ID_FKEY
import au.concepta.sakila.database.keys.PAYMENT_P2022_06__PAYMENT_P2022_06_RENTAL_ID_FKEY
import au.concepta.sakila.database.keys.PAYMENT_P2022_06__PAYMENT_P2022_06_STAFF_ID_FKEY
import au.concepta.sakila.database.tables.Customer.CustomerPath
import au.concepta.sakila.database.tables.Rental.RentalPath
import au.concepta.sakila.database.tables.Staff.StaffPath
import au.concepta.sakila.database.tables.records.PaymentP2022_06Record

import java.math.BigDecimal
import java.time.OffsetDateTime

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.Index
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class PaymentP2022_06(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, PaymentP2022_06Record>?,
    parentPath: InverseForeignKey<out Record, PaymentP2022_06Record>?,
    aliased: Table<PaymentP2022_06Record>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<PaymentP2022_06Record>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.payment_p2022_06</code>
         */
        val PAYMENT_P2022_06: PaymentP2022_06 = PaymentP2022_06()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<PaymentP2022_06Record> = PaymentP2022_06Record::class.java

    /**
     * The column <code>public.payment_p2022_06.payment_id</code>.
     */
    val PAYMENT_ID: TableField<PaymentP2022_06Record, Int?> = createField(DSL.name("payment_id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "")

    /**
     * The column <code>public.payment_p2022_06.customer_id</code>.
     */
    val CUSTOMER_ID: TableField<PaymentP2022_06Record, Int?> = createField(DSL.name("customer_id"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>public.payment_p2022_06.staff_id</code>.
     */
    val STAFF_ID: TableField<PaymentP2022_06Record, Int?> = createField(DSL.name("staff_id"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>public.payment_p2022_06.rental_id</code>.
     */
    val RENTAL_ID: TableField<PaymentP2022_06Record, Int?> = createField(DSL.name("rental_id"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>public.payment_p2022_06.amount</code>.
     */
    val AMOUNT: TableField<PaymentP2022_06Record, BigDecimal?> = createField(DSL.name("amount"), SQLDataType.NUMERIC(5, 2).nullable(false), this, "")

    /**
     * The column <code>public.payment_p2022_06.payment_date</code>.
     */
    val PAYMENT_DATE: TableField<PaymentP2022_06Record, OffsetDateTime?> = createField(DSL.name("payment_date"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).nullable(false), this, "")

    private constructor(alias: Name, aliased: Table<PaymentP2022_06Record>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<PaymentP2022_06Record>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<PaymentP2022_06Record>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.payment_p2022_06</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.payment_p2022_06</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.payment_p2022_06</code> table reference
     */
    constructor(): this(DSL.name("payment_p2022_06"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, PaymentP2022_06Record>?, parentPath: InverseForeignKey<out Record, PaymentP2022_06Record>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, PAYMENT_P2022_06, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class PaymentP2022_06Path : PaymentP2022_06, Path<PaymentP2022_06Record> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, PaymentP2022_06Record>?, parentPath: InverseForeignKey<out Record, PaymentP2022_06Record>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<PaymentP2022_06Record>): super(alias, aliased)
        override fun `as`(alias: String): PaymentP2022_06Path = PaymentP2022_06Path(DSL.name(alias), this)
        override fun `as`(alias: Name): PaymentP2022_06Path = PaymentP2022_06Path(alias, this)
        override fun `as`(alias: Table<*>): PaymentP2022_06Path = PaymentP2022_06Path(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIndexes(): List<Index> = listOf(IDX_FK_PAYMENT_P2022_06_CUSTOMER_ID, IDX_FK_PAYMENT_P2022_06_STAFF_ID, PAYMENT_P2022_06_CUSTOMER_ID_IDX)
    override fun getIdentity(): Identity<PaymentP2022_06Record, Int?> = super.getIdentity() as Identity<PaymentP2022_06Record, Int?>
    override fun getPrimaryKey(): UniqueKey<PaymentP2022_06Record> = PAYMENT_P2022_06_PKEY
    override fun getReferences(): List<ForeignKey<PaymentP2022_06Record, *>> = listOf(PAYMENT_P2022_06__PAYMENT_P2022_06_CUSTOMER_ID_FKEY, PAYMENT_P2022_06__PAYMENT_P2022_06_RENTAL_ID_FKEY, PAYMENT_P2022_06__PAYMENT_P2022_06_STAFF_ID_FKEY)

    /**
     * Get the implicit join path to the <code>public.customer</code> table.
     */
    fun customer(): CustomerPath = customer
    val customer: CustomerPath by lazy { CustomerPath(this, PAYMENT_P2022_06__PAYMENT_P2022_06_CUSTOMER_ID_FKEY, null) }

    /**
     * Get the implicit join path to the <code>public.rental</code> table.
     */
    fun rental(): RentalPath = rental
    val rental: RentalPath by lazy { RentalPath(this, PAYMENT_P2022_06__PAYMENT_P2022_06_RENTAL_ID_FKEY, null) }

    /**
     * Get the implicit join path to the <code>public.staff</code> table.
     */
    fun staff(): StaffPath = staff
    val staff: StaffPath by lazy { StaffPath(this, PAYMENT_P2022_06__PAYMENT_P2022_06_STAFF_ID_FKEY, null) }
    override fun `as`(alias: String): PaymentP2022_06 = PaymentP2022_06(DSL.name(alias), this)
    override fun `as`(alias: Name): PaymentP2022_06 = PaymentP2022_06(alias, this)
    override fun `as`(alias: Table<*>): PaymentP2022_06 = PaymentP2022_06(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): PaymentP2022_06 = PaymentP2022_06(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): PaymentP2022_06 = PaymentP2022_06(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): PaymentP2022_06 = PaymentP2022_06(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): PaymentP2022_06 = PaymentP2022_06(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): PaymentP2022_06 = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): PaymentP2022_06 = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): PaymentP2022_06 = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): PaymentP2022_06 = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): PaymentP2022_06 = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): PaymentP2022_06 = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): PaymentP2022_06 = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): PaymentP2022_06 = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): PaymentP2022_06 = where(DSL.notExists(select))
}
