/*
 * This file is generated by jOOQ.
 */
package au.concepta.sakila.database.tables


import au.concepta.sakila.database.Public
import au.concepta.sakila.database.tables.records.CustomerRecord

import java.math.BigDecimal
import java.time.LocalDate
import java.time.OffsetDateTime

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.Identity
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Record
import org.jooq.Schema
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.impl.DSL
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class RewardsReport(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, CustomerRecord>?,
    parentPath: InverseForeignKey<out Record, CustomerRecord>?,
    aliased: Table<CustomerRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<CustomerRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.function(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.rewards_report</code>
         */
        val REWARDS_REPORT: RewardsReport = RewardsReport()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<CustomerRecord> = CustomerRecord::class.java

    /**
     * The column <code>public.rewards_report.customer_id</code>.
     */
    val CUSTOMER_ID: TableField<CustomerRecord, Int?> = createField(DSL.name("customer_id"), SQLDataType.INTEGER.nullable(false).identity(true).defaultValue(DSL.field(DSL.raw("nextval('customer_customer_id_seq'::regclass)"), SQLDataType.INTEGER)), this, "")

    /**
     * The column <code>public.rewards_report.store_id</code>.
     */
    val STORE_ID: TableField<CustomerRecord, Int?> = createField(DSL.name("store_id"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>public.rewards_report.first_name</code>.
     */
    val FIRST_NAME: TableField<CustomerRecord, String?> = createField(DSL.name("first_name"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column <code>public.rewards_report.last_name</code>.
     */
    val LAST_NAME: TableField<CustomerRecord, String?> = createField(DSL.name("last_name"), SQLDataType.CLOB.nullable(false), this, "")

    /**
     * The column <code>public.rewards_report.email</code>.
     */
    val EMAIL: TableField<CustomerRecord, String?> = createField(DSL.name("email"), SQLDataType.CLOB, this, "")

    /**
     * The column <code>public.rewards_report.address_id</code>.
     */
    val ADDRESS_ID: TableField<CustomerRecord, Int?> = createField(DSL.name("address_id"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>public.rewards_report.activebool</code>.
     */
    val ACTIVEBOOL: TableField<CustomerRecord, Boolean?> = createField(DSL.name("activebool"), SQLDataType.BOOLEAN.nullable(false).defaultValue(DSL.field(DSL.raw("true"), SQLDataType.BOOLEAN)), this, "")

    /**
     * The column <code>public.rewards_report.create_date</code>.
     */
    val CREATE_DATE: TableField<CustomerRecord, LocalDate?> = createField(DSL.name("create_date"), SQLDataType.LOCALDATE.nullable(false).defaultValue(DSL.field(DSL.raw("CURRENT_DATE"), SQLDataType.LOCALDATE)), this, "")

    /**
     * The column <code>public.rewards_report.last_update</code>.
     */
    val LAST_UPDATE: TableField<CustomerRecord, OffsetDateTime?> = createField(DSL.name("last_update"), SQLDataType.TIMESTAMPWITHTIMEZONE(6).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.TIMESTAMPWITHTIMEZONE)), this, "")

    /**
     * The column <code>public.rewards_report.active</code>.
     */
    val ACTIVE: TableField<CustomerRecord, Int?> = createField(DSL.name("active"), SQLDataType.INTEGER, this, "")

    private constructor(alias: Name, aliased: Table<CustomerRecord>?): this(alias, null, null, null, aliased, arrayOf(
        DSL.value(null, SQLDataType.INTEGER),
        DSL.value(null, SQLDataType.NUMERIC)
    ), null)
    private constructor(alias: Name, aliased: Table<CustomerRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)

    /**
     * Create an aliased <code>public.rewards_report</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.rewards_report</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.rewards_report</code> table reference
     */
    constructor(): this(DSL.name("rewards_report"), null)
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getIdentity(): Identity<CustomerRecord, Int?> = super.getIdentity() as Identity<CustomerRecord, Int?>
    override fun `as`(alias: String): RewardsReport = RewardsReport(DSL.name(alias), this, parameters)
    override fun `as`(alias: Name): RewardsReport = RewardsReport(alias, this, parameters)
    override fun `as`(alias: Table<*>): RewardsReport = RewardsReport(alias.qualifiedName, this, parameters)

    /**
     * Rename this table
     */
    override fun rename(name: String): RewardsReport = RewardsReport(DSL.name(name), null, parameters)

    /**
     * Rename this table
     */
    override fun rename(name: Name): RewardsReport = RewardsReport(name, null, parameters)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): RewardsReport = RewardsReport(name.qualifiedName, null, parameters)

    /**
     * Call this table-valued function
     */
    fun call(
          minMonthlyPurchases: Int?
        , minDollarAmountPurchased: BigDecimal?
    ): RewardsReport = RewardsReport(DSL.name("rewards_report"), null, arrayOf(
        DSL.value(minMonthlyPurchases, SQLDataType.INTEGER),
        DSL.value(minDollarAmountPurchased, SQLDataType.NUMERIC)
    )).let { if (aliased()) it.`as`(unqualifiedName) else it }

    /**
     * Call this table-valued function
     */
    fun call(
          minMonthlyPurchases: Field<Int?>
        , minDollarAmountPurchased: Field<BigDecimal?>
    ): RewardsReport = RewardsReport(DSL.name("rewards_report"), null, arrayOf(
        minMonthlyPurchases,
        minDollarAmountPurchased
    )).let { if (aliased()) it.`as`(unqualifiedName) else it }
}
