/*
 * This file is generated by jOOQ.
 */
package au.concepta.sakila.database.tables.records


import au.concepta.sakila.database.tables.ActorInfo

import org.jooq.impl.TableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class ActorInfoRecord() : TableRecordImpl<ActorInfoRecord>(ActorInfo.ACTOR_INFO) {

    open var actorId: Int?
        set(value): Unit = set(0, value)
        get(): Int? = get(0) as Int?

    open var firstName: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var lastName: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open var filmInfo: String?
        set(value): Unit = set(3, value)
        get(): String? = get(3) as String?

    /**
     * Create a detached, initialised ActorInfoRecord
     */
    constructor(actorId: Int? = null, firstName: String? = null, lastName: String? = null, filmInfo: String? = null): this() {
        this.actorId = actorId
        this.firstName = firstName
        this.lastName = lastName
        this.filmInfo = filmInfo
        resetTouchedOnNotNull()
    }
}
