/*
 * This file is generated by jOOQ.
 */
package au.concepta.sakila.database.tables.records


import au.concepta.sakila.database.tables.City

import java.time.OffsetDateTime

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class CityRecord() : UpdatableRecordImpl<CityRecord>(City.CITY) {

    open var cityId: Int?
        set(value): Unit = set(0, value)
        get(): Int? = get(0) as Int?

    open var city: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var countryId: Int?
        set(value): Unit = set(2, value)
        get(): Int? = get(2) as Int?

    open var lastUpdate: OffsetDateTime?
        set(value): Unit = set(3, value)
        get(): OffsetDateTime? = get(3) as OffsetDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Int?> = super.key() as Record1<Int?>

    /**
     * Create a detached, initialised CityRecord
     */
    constructor(cityId: Int? = null, city: String? = null, countryId: Int? = null, lastUpdate: OffsetDateTime? = null): this() {
        this.cityId = cityId
        this.city = city
        this.countryId = countryId
        this.lastUpdate = lastUpdate
        resetTouchedOnNotNull()
    }
}
