/*
 * This file is generated by jOOQ.
 */
package au.concepta.sakila.database.tables.records


import au.concepta.sakila.database.tables.Country

import java.time.OffsetDateTime

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class CountryRecord() : UpdatableRecordImpl<CountryRecord>(Country.COUNTRY) {

    open var countryId: Int?
        set(value): Unit = set(0, value)
        get(): Int? = get(0) as Int?

    open var country: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var lastUpdate: OffsetDateTime?
        set(value): Unit = set(2, value)
        get(): OffsetDateTime? = get(2) as OffsetDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Int?> = super.key() as Record1<Int?>

    /**
     * Create a detached, initialised CountryRecord
     */
    constructor(countryId: Int? = null, country: String? = null, lastUpdate: OffsetDateTime? = null): this() {
        this.countryId = countryId
        this.country = country
        this.lastUpdate = lastUpdate
        resetTouchedOnNotNull()
    }
}
