/*
 * This file is generated by jOOQ.
 */
package au.concepta.sakila.database.tables.records


import au.concepta.sakila.database.tables.Customer

import java.time.LocalDate
import java.time.OffsetDateTime

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class CustomerRecord() : UpdatableRecordImpl<CustomerRecord>(Customer.CUSTOMER) {

    open var customerId: Int?
        set(value): Unit = set(0, value)
        get(): Int? = get(0) as Int?

    open var storeId: Int?
        set(value): Unit = set(1, value)
        get(): Int? = get(1) as Int?

    open var firstName: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open var lastName: String?
        set(value): Unit = set(3, value)
        get(): String? = get(3) as String?

    open var email: String?
        set(value): Unit = set(4, value)
        get(): String? = get(4) as String?

    open var addressId: Int?
        set(value): Unit = set(5, value)
        get(): Int? = get(5) as Int?

    open var activebool: Boolean?
        set(value): Unit = set(6, value)
        get(): Boolean? = get(6) as Boolean?

    open var createDate: LocalDate?
        set(value): Unit = set(7, value)
        get(): LocalDate? = get(7) as LocalDate?

    open var lastUpdate: OffsetDateTime?
        set(value): Unit = set(8, value)
        get(): OffsetDateTime? = get(8) as OffsetDateTime?

    open var active: Int?
        set(value): Unit = set(9, value)
        get(): Int? = get(9) as Int?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Int?> = super.key() as Record1<Int?>

    /**
     * Create a detached, initialised CustomerRecord
     */
    constructor(customerId: Int? = null, storeId: Int? = null, firstName: String? = null, lastName: String? = null, email: String? = null, addressId: Int? = null, activebool: Boolean? = null, createDate: LocalDate? = null, lastUpdate: OffsetDateTime? = null, active: Int? = null): this() {
        this.customerId = customerId
        this.storeId = storeId
        this.firstName = firstName
        this.lastName = lastName
        this.email = email
        this.addressId = addressId
        this.activebool = activebool
        this.createDate = createDate
        this.lastUpdate = lastUpdate
        this.active = active
        resetTouchedOnNotNull()
    }
}
