/*
 * This file is generated by jOOQ.
 */
package au.concepta.sakila.database.tables.records


import au.concepta.sakila.database.tables.FilmActor

import java.time.OffsetDateTime

import org.jooq.Record2
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class FilmActorRecord() : UpdatableRecordImpl<FilmActorRecord>(FilmActor.FILM_ACTOR) {

    open var actorId: Int?
        set(value): Unit = set(0, value)
        get(): Int? = get(0) as Int?

    open var filmId: Int?
        set(value): Unit = set(1, value)
        get(): Int? = get(1) as Int?

    open var lastUpdate: OffsetDateTime?
        set(value): Unit = set(2, value)
        get(): OffsetDateTime? = get(2) as OffsetDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record2<Int?, Int?> = super.key() as Record2<Int?, Int?>

    /**
     * Create a detached, initialised FilmActorRecord
     */
    constructor(actorId: Int? = null, filmId: Int? = null, lastUpdate: OffsetDateTime? = null): this() {
        this.actorId = actorId
        this.filmId = filmId
        this.lastUpdate = lastUpdate
        resetTouchedOnNotNull()
    }
}
