/*
 * This file is generated by jOOQ.
 */
package au.concepta.sakila.database.tables.records


import au.concepta.sakila.database.tables.RentalByCategory

import java.math.BigDecimal

import org.jooq.impl.TableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class RentalByCategoryRecord() : TableRecordImpl<RentalByCategoryRecord>(RentalByCategory.RENTAL_BY_CATEGORY) {

    open var category: String?
        set(value): Unit = set(0, value)
        get(): String? = get(0) as String?

    open var totalSales: BigDecimal?
        set(value): Unit = set(1, value)
        get(): BigDecimal? = get(1) as BigDecimal?

    /**
     * Create a detached, initialised RentalByCategoryRecord
     */
    constructor(category: String? = null, totalSales: BigDecimal? = null): this() {
        this.category = category
        this.totalSales = totalSales
        resetTouchedOnNotNull()
    }
}
