/*
 * This file is generated by jOOQ.
 */
package au.concepta.sakila.database.tables.records


import au.concepta.sakila.database.tables.SalesByStore

import java.math.BigDecimal

import org.jooq.impl.TableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class SalesByStoreRecord() : TableRecordImpl<SalesByStoreRecord>(SalesByStore.SALES_BY_STORE) {

    open var store: String?
        set(value): Unit = set(0, value)
        get(): String? = get(0) as String?

    open var manager: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var totalSales: BigDecimal?
        set(value): Unit = set(2, value)
        get(): BigDecimal? = get(2) as BigDecimal?

    /**
     * Create a detached, initialised SalesByStoreRecord
     */
    constructor(store: String? = null, manager: String? = null, totalSales: BigDecimal? = null): this() {
        this.store = store
        this.manager = manager
        this.totalSales = totalSales
        resetTouchedOnNotNull()
    }
}
