/*
 * This file is generated by jOOQ.
 */
package au.concepta.sakila.database.tables.records


import au.concepta.sakila.database.tables.Store

import java.time.OffsetDateTime

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class StoreRecord() : UpdatableRecordImpl<StoreRecord>(Store.STORE) {

    open var storeId: Int?
        set(value): Unit = set(0, value)
        get(): Int? = get(0) as Int?

    open var managerStaffId: Int?
        set(value): Unit = set(1, value)
        get(): Int? = get(1) as Int?

    open var addressId: Int?
        set(value): Unit = set(2, value)
        get(): Int? = get(2) as Int?

    open var lastUpdate: OffsetDateTime?
        set(value): Unit = set(3, value)
        get(): OffsetDateTime? = get(3) as OffsetDateTime?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Int?> = super.key() as Record1<Int?>

    /**
     * Create a detached, initialised StoreRecord
     */
    constructor(storeId: Int? = null, managerStaffId: Int? = null, addressId: Int? = null, lastUpdate: OffsetDateTime? = null): this() {
        this.storeId = storeId
        this.managerStaffId = managerStaffId
        this.addressId = addressId
        this.lastUpdate = lastUpdate
        resetTouchedOnNotNull()
    }
}
