@file:Suppress("warnings")
/*
 * This file is generated by jOOQ.
 */
package au.concepta.sakila.database.routines.references


import au.concepta.sakila.database.routines.GetCustomerBalance
import au.concepta.sakila.database.routines.GroupConcat
import au.concepta.sakila.database.routines.InventoryHeldByCustomer
import au.concepta.sakila.database.routines.InventoryInStock
import au.concepta.sakila.database.routines.LastDay
import au.concepta.sakila.database.routines._GroupConcat
import au.concepta.sakila.database.tables.FilmInStock
import au.concepta.sakila.database.tables.FilmNotInStock
import au.concepta.sakila.database.tables.RewardsReport
import au.concepta.sakila.database.tables.records.CustomerRecord
import au.concepta.sakila.database.tables.records.FilmInStockRecord
import au.concepta.sakila.database.tables.records.FilmNotInStockRecord

import java.math.BigDecimal
import java.time.LocalDate
import java.time.OffsetDateTime

import org.jooq.AggregateFunction
import org.jooq.Configuration
import org.jooq.Field
import org.jooq.Result



/**
 * Call <code>public._group_concat</code>
 */
fun _GroupConcat(
      configuration: Configuration
    , __1: String?
    , __2: String?
): String? {
    val f = _GroupConcat()
    f.set__1(__1)
    f.set__2(__2)

    f.execute(configuration)
    return f.returnValue
}

/**
 * Get <code>public._group_concat</code> as a field.
 */
fun _GroupConcat(
      __1: String?
    , __2: String?
): Field<String?> {
    val f = _GroupConcat()
    f.set__1(__1)
    f.set__2(__2)

    return f.asField()
}

/**
 * Get <code>public._group_concat</code> as a field.
 */
fun _GroupConcat(
      __1: Field<String?>
    , __2: Field<String?>
): Field<String?> {
    val f = _GroupConcat()
    f.set__1(__1)
    f.set__2(__2)

    return f.asField()
}

/**
 * Call <code>public.get_customer_balance</code>
 */
fun getCustomerBalance(
      configuration: Configuration
    , pCustomerId: Int?
    , pEffectiveDate: OffsetDateTime?
): BigDecimal? {
    val f = GetCustomerBalance()
    f.setPCustomerId(pCustomerId)
    f.setPEffectiveDate(pEffectiveDate)

    f.execute(configuration)
    return f.returnValue
}

/**
 * Get <code>public.get_customer_balance</code> as a field.
 */
fun getCustomerBalance(
      pCustomerId: Int?
    , pEffectiveDate: OffsetDateTime?
): Field<BigDecimal?> {
    val f = GetCustomerBalance()
    f.setPCustomerId(pCustomerId)
    f.setPEffectiveDate(pEffectiveDate)

    return f.asField()
}

/**
 * Get <code>public.get_customer_balance</code> as a field.
 */
fun getCustomerBalance(
      pCustomerId: Field<Int?>
    , pEffectiveDate: Field<OffsetDateTime?>
): Field<BigDecimal?> {
    val f = GetCustomerBalance()
    f.setPCustomerId(pCustomerId)
    f.setPEffectiveDate(pEffectiveDate)

    return f.asField()
}

/**
 * Get <code>public.group_concat</code> as a field.
 */
fun groupConcat(
      __1: String?
): AggregateFunction<String?> {
    val f = GroupConcat()
    f.set__1(__1)

    return f.asAggregateFunction()
}

/**
 * Get <code>public.group_concat</code> as a field.
 */
fun groupConcat(
      __1: Field<String?>
): AggregateFunction<String?> {
    val f = GroupConcat()
    f.set__1(__1)

    return f.asAggregateFunction()
}

/**
 * Call <code>public.inventory_held_by_customer</code>
 */
fun inventoryHeldByCustomer(
      configuration: Configuration
    , pInventoryId: Int?
): Int? {
    val f = InventoryHeldByCustomer()
    f.setPInventoryId(pInventoryId)

    f.execute(configuration)
    return f.returnValue
}

/**
 * Get <code>public.inventory_held_by_customer</code> as a field.
 */
fun inventoryHeldByCustomer(
      pInventoryId: Int?
): Field<Int?> {
    val f = InventoryHeldByCustomer()
    f.setPInventoryId(pInventoryId)

    return f.asField()
}

/**
 * Get <code>public.inventory_held_by_customer</code> as a field.
 */
fun inventoryHeldByCustomer(
      pInventoryId: Field<Int?>
): Field<Int?> {
    val f = InventoryHeldByCustomer()
    f.setPInventoryId(pInventoryId)

    return f.asField()
}

/**
 * Call <code>public.inventory_in_stock</code>
 */
fun inventoryInStock(
      configuration: Configuration
    , pInventoryId: Int?
): Boolean? {
    val f = InventoryInStock()
    f.setPInventoryId(pInventoryId)

    f.execute(configuration)
    return f.returnValue
}

/**
 * Get <code>public.inventory_in_stock</code> as a field.
 */
fun inventoryInStock(
      pInventoryId: Int?
): Field<Boolean?> {
    val f = InventoryInStock()
    f.setPInventoryId(pInventoryId)

    return f.asField()
}

/**
 * Get <code>public.inventory_in_stock</code> as a field.
 */
fun inventoryInStock(
      pInventoryId: Field<Int?>
): Field<Boolean?> {
    val f = InventoryInStock()
    f.setPInventoryId(pInventoryId)

    return f.asField()
}

/**
 * Call <code>public.last_day</code>
 */
fun lastDay(
      configuration: Configuration
    , __1: OffsetDateTime?
): LocalDate? {
    val f = LastDay()
    f.set__1(__1)

    f.execute(configuration)
    return f.returnValue
}

/**
 * Get <code>public.last_day</code> as a field.
 */
fun lastDay(
      __1: OffsetDateTime?
): Field<LocalDate?> {
    val f = LastDay()
    f.set__1(__1)

    return f.asField()
}

/**
 * Get <code>public.last_day</code> as a field.
 */
fun lastDay(
      __1: Field<OffsetDateTime?>
): Field<LocalDate?> {
    val f = LastDay()
    f.set__1(__1)

    return f.asField()
}

/**
 * Call <code>public.film_in_stock</code>.
 */
fun filmInStock(
      configuration: Configuration
    , pFilmId: Int?
    , pStoreId: Int?
): Result<FilmInStockRecord> = configuration.dsl().selectFrom(au.concepta.sakila.database.tables.FilmInStock.FILM_IN_STOCK.call(
      pFilmId
    , pStoreId
)).fetch()

/**
 * Get <code>public.film_in_stock</code> as a table.
 */
fun filmInStock(
      pFilmId: Int?
    , pStoreId: Int?
): FilmInStock = au.concepta.sakila.database.tables.FilmInStock.FILM_IN_STOCK.call(
    pFilmId,
    pStoreId
)

/**
 * Get <code>public.film_in_stock</code> as a table.
 */
fun filmInStock(
      pFilmId: Field<Int?>
    , pStoreId: Field<Int?>
): FilmInStock = au.concepta.sakila.database.tables.FilmInStock.FILM_IN_STOCK.call(
    pFilmId,
    pStoreId
)

/**
 * Call <code>public.film_not_in_stock</code>.
 */
fun filmNotInStock(
      configuration: Configuration
    , pFilmId: Int?
    , pStoreId: Int?
): Result<FilmNotInStockRecord> = configuration.dsl().selectFrom(au.concepta.sakila.database.tables.FilmNotInStock.FILM_NOT_IN_STOCK.call(
      pFilmId
    , pStoreId
)).fetch()

/**
 * Get <code>public.film_not_in_stock</code> as a table.
 */
fun filmNotInStock(
      pFilmId: Int?
    , pStoreId: Int?
): FilmNotInStock = au.concepta.sakila.database.tables.FilmNotInStock.FILM_NOT_IN_STOCK.call(
    pFilmId,
    pStoreId
)

/**
 * Get <code>public.film_not_in_stock</code> as a table.
 */
fun filmNotInStock(
      pFilmId: Field<Int?>
    , pStoreId: Field<Int?>
): FilmNotInStock = au.concepta.sakila.database.tables.FilmNotInStock.FILM_NOT_IN_STOCK.call(
    pFilmId,
    pStoreId
)

/**
 * Call <code>public.rewards_report</code>.
 */
fun rewardsReport(
      configuration: Configuration
    , minMonthlyPurchases: Int?
    , minDollarAmountPurchased: BigDecimal?
): Result<CustomerRecord> = configuration.dsl().selectFrom(au.concepta.sakila.database.tables.RewardsReport.REWARDS_REPORT.call(
      minMonthlyPurchases
    , minDollarAmountPurchased
)).fetch()

/**
 * Get <code>public.rewards_report</code> as a table.
 */
fun rewardsReport(
      minMonthlyPurchases: Int?
    , minDollarAmountPurchased: BigDecimal?
): RewardsReport = au.concepta.sakila.database.tables.RewardsReport.REWARDS_REPORT.call(
    minMonthlyPurchases,
    minDollarAmountPurchased
)

/**
 * Get <code>public.rewards_report</code> as a table.
 */
fun rewardsReport(
      minMonthlyPurchases: Field<Int?>
    , minDollarAmountPurchased: Field<BigDecimal?>
): RewardsReport = au.concepta.sakila.database.tables.RewardsReport.REWARDS_REPORT.call(
    minMonthlyPurchases,
    minDollarAmountPurchased
)
