name: Build and Test Frontend

on:
  push:
    paths:
      - 'shared/**'
      - 'webApp/**'
      - '.github/workflows/build-and-test-frontend.yml'
      - 'package.json'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./webApp
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
      # Running `npm ci` seems to be missing out on the Svelte-MUI dev files and fails the check step
      - run: npm install --include=dev
      - run: npm run lint
      - run: npm run check
      - run: npm run build
