name: Build and Test Frontend

on:
  push:
    paths:
      - 'shared/**'
      - 'webApp/**'
      - '.github/workflows/build-and-test-frontend.yml'
      - 'package.json'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./webApp
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v7
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@5e2ebd065dc2488b7a6ad670704656cbbe1e8f60 # v6.1.1

      - name: Build shared libraries
        working-directory: .
        run:
          ./gradlew kotlinUpgradeYarnLock :shared:jsBrowserDevelopmentLibraryDistribution

      - name: Stop Gradle Daemon
        working-directory: .
        run: ./gradlew --stop

      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - run: npm ci
      - run: npm run lint
      - run: npm run check
      - run: npm run build
