name: Build and Test Frontend

on:
  push:
    paths:
      - 'shared/**'
      - 'webApp/**'
      - '.github/workflows/build-and-test-frontend.yml'
      - 'package.json'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./webApp
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v6
      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@39e147cb9de83bb9910b8ef8bd7fff0ee20fcd6f # v6.0.1

      - name: Build shared libraries
        working-directory: .
        run:
          ./gradlew :shared:jsBrowserDevelopmentLibraryDistribution

      - uses: actions/setup-node@v6
        with:
          node-version: 24
      - run: npm ci
      - run: npm run lint
      - run: npm run check
      - run: npm run build
